### ISSUE TITLE
Callysto Hub Logo Position

### ISSUE THREAD

**Issue by inygy** [callysto/hub-landing-page#2]
The hub logo is overlapping the top bar on the website and slightly off the page. Screen resolution is 1366 x 768
![hublogoissue](https://user-images.githubusercontent.com/32275839/40627868-49c25324-6276-11e8-9a87-2975b8d24df2.PNG)

**Comment by ianabc** [comment]
Moved this to hugo so lots of things will change. At 1366x768 the logo tucks behind the nav bar now.
